# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v4.0.1
        hooks:
        -   id: trailing-whitespace
        -   id: end-of-file-fixer
        -   id: check-yaml
        -   id: check-case-conflict
        -   id: debug-statements
        -   id: detect-private-key
        -   id: check-merge-conflict
        -   id: check-added-large-files
        -   id: detect-aws-credentials
    -   repo: https://github.com/myint/autoflake
        rev: v1.4
        hooks:
        -   id: autoflake
            args:
              - --in-place
              - --remove-duplicate-keys
              - --remove-unused-variables
              - --remove-all-unused-imports
              - --expand-star-imports
    -   repo: https://github.com/PyCQA/isort
        rev: 5.9.1
        hooks:
        -   id: isort
            args:
              - --profile
              - black
    -   repo: https://github.com/ambv/black
        rev: 22.3.0
        hooks:
        -   id: black
